### ISSUE TITLE
Feilsøke hvorfor mobiltelefonnummeret noen gang forsvinner..

### ISSUE THREAD

**Issue by linesharina** [b019-g13/Sirkus-Media-nettsted-front-end#21]

**Comment by linesharina** [comment]
I headeren. F.eks. om man bruker "Hopp til innhold"-knappen

**Comment by bjornarhagen** [comment]
Klarer ikke finne ut av dette.

Ser at render() i Page.js kjører når man trykker på en link.
Deretter kjører ComponentWillUnmount() i komponenten som forsvinner, men finner ikke ut hvorfor...
